#!/usr/bin/env bash
set -euo pipefail

REPO="${WAYPOINT_INSTALL_REPO:-logbookfordevs/logbook-waypoint}"
VERSION="${WAYPOINT_INSTALL_VERSION:-latest}"
ASSET_NAME="${WAYPOINT_INSTALL_ASSET:-waypoint-cli.tar.gz}"
INSTALL_ROOT="${WAYPOINT_INSTALL_ROOT:-$HOME/.local/share/logbook-waypoint}"
BIN_DIR="${WAYPOINT_BIN_DIR:-$HOME/.local/bin}"
BIN_PATH="$BIN_DIR/waypoint"
UNLINK_MODE=0

info() {
  printf '\033[1;36m%s\033[0m %s\n' "waypoint" "$1"
}

fail() {
  printf '\033[1;31m%s\033[0m %s\n' "waypoint" "$1" >&2
  exit 1
}

usage() {
  cat <<'USAGE'
Usage: install.sh [options]

Install a Logbook Waypoint CLI release from GitHub.

Options:
  --version <tag>         Release tag to install. Defaults to latest.
  --repo <owner/name>     GitHub repository to install from.
  --asset <name>          Release asset name. Defaults to waypoint-cli.tar.gz.
  --install-root <path>   Directory where Waypoint releases are stored.
  --bin-dir <path>        Directory where the waypoint launcher is written.
  --unlink                Remove the launcher written by this installer.
  -h, --help              Show this help and exit.

Examples:
  curl -fsSL https://waypoint.logbookfordevs.com/install.sh | bash
  ./scripts/install.sh --version v0.1.1
  ./scripts/install.sh --unlink
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      [[ -n "${2:-}" ]] || fail "--version requires a value"
      VERSION="$2"
      shift 2
      ;;
    --version=*) VERSION="${1#--version=}"; shift ;;
    --repo)
      [[ -n "${2:-}" ]] || fail "--repo requires a value"
      REPO="$2"
      shift 2
      ;;
    --repo=*) REPO="${1#--repo=}"; shift ;;
    --asset)
      [[ -n "${2:-}" ]] || fail "--asset requires a value"
      ASSET_NAME="$2"
      shift 2
      ;;
    --asset=*) ASSET_NAME="${1#--asset=}"; shift ;;
    --install-root)
      [[ -n "${2:-}" ]] || fail "--install-root requires a value"
      INSTALL_ROOT="$2"
      shift 2
      ;;
    --install-root=*) INSTALL_ROOT="${1#--install-root=}"; shift ;;
    --bin-dir)
      [[ -n "${2:-}" ]] || fail "--bin-dir requires a value"
      BIN_DIR="$2"
      BIN_PATH="$BIN_DIR/waypoint"
      shift 2
      ;;
    --bin-dir=*)
      BIN_DIR="${1#--bin-dir=}"
      BIN_PATH="$BIN_DIR/waypoint"
      shift
      ;;
    --unlink) UNLINK_MODE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) fail "unknown option: $1" ;;
  esac
done

require_node() {
  if ! command -v node >/dev/null 2>&1; then
    fail "node >=18 is required to run Logbook Waypoint"
  fi

  local major
  major="$(node -p 'Number(process.versions.node.split(".")[0])' 2>/dev/null || true)"
  if [[ -z "$major" || "$major" -lt 18 ]]; then
    fail "node >=18 is required; found $(node --version 2>/dev/null || printf 'unknown')"
  fi
}

resolve_latest_version() {
  local latest_url="https://github.com/$REPO/releases/latest"
  local resolved_url
  resolved_url="$(curl -fsSL -o /dev/null -w '%{url_effective}' "$latest_url")" || fail "could not resolve latest release for $REPO"

  local tag_prefix="https://github.com/$REPO/releases/tag/"
  case "$resolved_url" in
    "$tag_prefix"*) ;;
    *) fail "could not resolve latest release for $REPO" ;;
  esac

  local resolved_version="${resolved_url#"$tag_prefix"}"
  case "$resolved_version" in
    ""|*/*|*\?*|*\#*) fail "could not resolve latest release for $REPO" ;;
  esac
  printf '%s' "$resolved_version"
}

write_launcher() {
  local entry_path="$1"
  [[ -f "$entry_path" ]] || fail "release asset did not contain bin/cli.js"

  mkdir -p "$BIN_DIR"
  local escaped_entry_path
  printf -v escaped_entry_path '%q' "$entry_path"
  cat > "$BIN_PATH" <<LAUNCHER
#!/usr/bin/env bash
set -euo pipefail
# Generated by Logbook Waypoint install.sh.
WAYPOINT_ENTRYPOINT=$escaped_entry_path

if ! command -v node >/dev/null 2>&1; then
  printf 'waypoint: node >=18 is required to run Logbook Waypoint.\n' >&2
  exit 1
fi

exec node "\$WAYPOINT_ENTRYPOINT" "\$@"
LAUNCHER
  chmod +x "$BIN_PATH"

  info "installed $BIN_PATH"
  case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) info "$BIN_DIR is not in PATH; add: export PATH=\"$BIN_DIR:\$PATH\"" ;;
  esac
}

unlink_launcher() {
  if [[ ! -e "$BIN_PATH" && ! -L "$BIN_PATH" ]]; then
    info "no installer-managed waypoint launcher found"
    return 0
  fi

  if [[ -L "$BIN_PATH" ]]; then
    case "$(readlink "$BIN_PATH")" in
      *node_modules/@logbookfordevs/waypoint*) fail "$BIN_PATH belongs to npm; refusing to remove it" ;;
    esac
  elif ! grep -q "Generated by Logbook Waypoint install.sh" "$BIN_PATH" 2>/dev/null; then
    fail "$BIN_PATH was not written by this installer; refusing to remove it"
  fi

  rm "$BIN_PATH"
  info "removed $BIN_PATH"
}

if [[ "$UNLINK_MODE" -eq 1 ]]; then
  unlink_launcher
  exit 0
fi

command -v curl >/dev/null 2>&1 || fail "curl is required to install Logbook Waypoint"
command -v tar >/dev/null 2>&1 || fail "tar is required to install Logbook Waypoint"
require_node

if [[ "$VERSION" = "latest" ]]; then
  info "fetching latest release"
  VERSION="$(resolve_latest_version)"
fi
case "$VERSION" in v*) ;; *) VERSION="v$VERSION" ;; esac

asset_url="https://github.com/$REPO/releases/download/$VERSION/$ASSET_NAME"
release_dir="$INSTALL_ROOT/releases/$VERSION"
tmp_dir="$(mktemp -d)"
archive_path="$tmp_dir/$ASSET_NAME"
cleanup() { rm -rf "$tmp_dir"; }
trap cleanup EXIT

info "downloading $REPO $VERSION"
curl -fL -o "$archive_path" "$asset_url"
checksum_text="$(curl -fsSL "$asset_url.sha256")" || fail "checksum asset is required"
expected_checksum="$(printf '%s\n' "$checksum_text" | awk '{print $1}' | head -n 1)"
[[ -n "$expected_checksum" ]] || fail "checksum asset is empty"

if [[ "$(uname -s)" = "Darwin" ]]; then
  actual_checksum="$(shasum -a 256 "$archive_path" | awk '{print $1}')"
else
  actual_checksum="$(sha256sum "$archive_path" | awk '{print $1}')"
fi
[[ "$actual_checksum" = "$expected_checksum" ]] || fail "checksum verification failed"
info "SHA256 verified"

rm -rf "$release_dir"
mkdir -p "$release_dir"
tar -xzf "$archive_path" -C "$release_dir"
write_launcher "$release_dir/bin/cli.js"
